version: '3.8'

services:
  firecrawl:
    image: mendable/firecrawl:latest
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=0.0.0.0
      - USE_DB_AUTHENTICATION=false
      - BULL_AUTH_KEY=CHANGEME
    depends_on:
      - redis
      - playwright-service

  playwright-service:
    image: mendable/firecrawl-playwright:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped 